site_name: www.technotes.ie
site_url: https://www.technotes.ie
theme:
  material
plugins:
  - diagrams:
      file_extension: ".diagrams.py"
      max_workers: 5
  - kroki:
      FileTypes:
        - svg
nav:
  - 'index.md'
  - 'helloworld':
    - 'helloworld/assembler.md'
    - 'helloworld/c.md'
    - 'helloworld/rust.md'
  - 'diagram_as_code.md'
  - 'kubernetes':
    - 'kubernetes/cluster_pi.md'
  - 'lets_encrypt.md'
  - 'mkdocs.md'
  - 'tech_humour.md'
